# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1005, 616)
        Form.setStyleSheet("QWidget, QFrame,QDialog\n"
"{\n"
"    background:#f2f2f2;\n"
"}\n"
"\n"
"QMainWindow\n"
"{\n"
"    background:#f2f2f2;\n"
"}\n"
"\n"
"QWebView\n"
"{\n"
"    background:#fefefe;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QStatusBar///////////////////////////////////////////*/ \n"
"QStatusBar \n"
"{\n"
"    border-top:1px solid #aaaaaa;\n"
"    min-height:20px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #f4f4f4, stop:1 #e4e4e4);/*渐变背景色*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////工具栏及窗口边框///////////////////////////////////////////*/ \n"
"/*窗口边框，可*/\n"
"QFrame#window\n"
"{\n"
"    padding:0px;\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-style:solid;/*边框类型*/\n"
"    /*用渐变色可以营造光晕边框效果*/\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #999999, stop:1 #ffffff)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #999999, stop:1 #ffffff)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #999999, stop:1 #ffffff)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #999999, stop:1 #ffffff);/*左边框渐变色*/\n"
"}\n"
"\n"
"QFrame#dialog,QFrame#messagebox\n"
"{\n"
"    padding:12px;/*设置透明阴影留出的padding空间，通过源码绘制透明阴影 注意在代码中设置QSSDIALOG_SHADOW_WIDTH为12*/\n"
"    border:0px solid #ff0000;/*指定边框为0，实际边框时绘制阴影时直接画de直线，边框颜色也是在代码中指定的*/\n"
"}\n"
"\n"
"/*标题栏*/\n"
"QWidget#titlebar\n"
"{\n"
"    min-height:25px;/*用min-height设置标题栏高度*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #e4e4e4, stop:1 #d4d4d4);/*渐变背景色*/\n"
"    border-bottom:1px solid #aaaaaa;\n"
"}\n"
"\n"
"QWidget:active#titlebar\n"
"{\n"
"    min-height:25px;/*用min-height设置标题栏高度*/\n"
"    \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #f4f4f4, stop:1 #e4e4e4);/*渐变背景色*/\n"
"    border-bottom:1px solid #aaaaaa;\n"
"}\n"
"\n"
"/*标题栏图标*/\n"
"QPushButton#titlebaricon\n"
"{\n"
"    min-width:24px;/*覆盖QPushButton中设置*/\n"
"    min-height:24px;/*覆盖QPushButton中设置*/\n"
"    width:24px;/*宽度*/\n"
"    height:24px;\n"
"    padding:0px;\n"
"    padding-left:2px;\n"
"    padding-right:-2px;\n"
"    background:transparent;/*无背景无边框*/\n"
"    border:none;\n"
"}\n"
"\n"
"/*标题栏标题*/\n"
"QLabel#titlebartitle\n"
"{\n"
"    padding-left:2px;\n"
"    font-weight:bold;\n"
"    font-size:10pt;\n"
"    color:#222222;\n"
"    background:transparent;\n"
"}\n"
"\n"
"/*标题栏关闭按钮*/\n"
"QPushButton#titlebarclosebtn\n"
"{\n"
"    padding:0px;\n"
"    padding-right:3px;\n"
"    min-width:39px;\n"
"    min-height:19px;\n"
"    width:39px;\n"
"    height:19px;\n"
"    outline:none;\n"
"    border: none;\n"
"    background:transparent;/*无背景无边框*/\n"
"    image:url(:/qss/icon/btn_close_highlight.png);/*btn_close_normal*/\n"
"}\n"
"\n"
"QPushButton#titlebarclosebtn:hover\n"
"{\n"
"    min-width:39px;\n"
"    min-height:19px;\n"
"    width:39px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_close_highlight.png);\n"
"}\n"
"\n"
"QPushButton#titlebarclosebtn:pressed\n"
"{\n"
"    min-width:39px;\n"
"    min-height:19px;\n"
"    width:39px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_close_down.png);\n"
"}\n"
"\n"
"/*标题栏最小化按钮*/\n"
"QPushButton#titlebarminbtn\n"
"{\n"
"    padding:0px;\n"
"    min-width:28px;\n"
"    min-height:19px;\n"
"    width:28px;\n"
"    height:19px;\n"
"    outline:none;\n"
"    border: none;\n"
"    background:transparent;\n"
"    image:url(:/qss/icon/btn_mini_normal.png);\n"
"}\n"
"\n"
"QPushButton#titlebarminbtn:hover\n"
"{\n"
"    min-width:28px;\n"
"    min-height:19px;\n"
"    width:28px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_mini_highlight.png);\n"
"}\n"
"\n"
"QPushButton#titlebarminbtn:pressed\n"
"{\n"
"    min-width:28px;\n"
"    min-height:19px;\n"
"    width:28px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_mini_down.png);\n"
"}\n"
"\n"
"/*标题栏最大化按钮*/\n"
"QPushButton#titlebarmaxbtn\n"
"{\n"
"    padding:0px;\n"
"    padding-bottom:3px;/*因为图表资源尺寸不对，做的微调*/\n"
"    border: none;    \n"
"    min-width:25px;\n"
"    min-height:18px;\n"
"    width:25px;\n"
"    height:18px;\n"
"    outline:none;\n"
"    background:transparent;\n"
"    image:url(:/qss/icon/btn_max_normal.png);\n"
"}\n"
"\n"
"QPushButton#titlebarmaxbtn:hover\n"
"{\n"
"    min-width:28px;\n"
"    min-height:19px;\n"
"    width:28px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_max_highlight.png);\n"
"}\n"
"\n"
"QPushButton#titlebarmaxbtn:pressed\n"
"{\n"
"    min-width:28px;\n"
"    min-height:19px;\n"
"    width:28px;\n"
"    height:19px;\n"
"    image:url(:/qss/icon/btn_max_down.png);\n"
"}\n"
"\n"
"/*标题栏还原按钮*/\n"
"QPushButton#titlebarrestorebtn\n"
"{\n"
"    padding:0px;\n"
"    padding-bottom:3px;/*因为图表资源尺寸不对，做的微调*/\n"
"    border: none;\n"
"    min-width:25px;\n"
"    min-height:18px;\n"
"    width:25px;\n"
"    height:18px;\n"
"    outline:none;\n"
"    background:transparent;\n"
"    image:url(:/qss/icon/btn_restore_normal.png);\n"
"}\n"
"\n"
"QPushButton#titlebarrestorebtn:hover\n"
"{\n"
"    min-width:28px;\n"
"    min-height:20px;\n"
"    width:28px;\n"
"    height:20px;\n"
"    image:url(:/qss/icon/btn_restore_highlight.png);\n"
"}\n"
"\n"
"QPushButton#titlebarrestorebtn:pressed\n"
"{\n"
"    min-width:28px;\n"
"    min-height:20px;\n"
"    width:28px;\n"
"    height:20px;\n"
"    image:url(:/qss/icon/btn_restore_down.png);\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QPushButton///////////////////////////////////////////*/\n"
"/*为QPushButton设置通用属性*/\n"
"QPushButton\n"
"{\n"
"    padding:0px 4px;/*上下padding为0px 左右未6px {1,4}为上右下左*/\n"
"    min-width:80;\n"
"    min-height:24;\n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    outline:none;/*表示foucs状态时取消虚线框*/\n"
"}\n"
"\n"
"QPushButton::disabled\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"/*为hover状态QPushButton设置属性，注意hover伪状态设置一定要在pressed伪状态之前！！！！！！！！！！*/\n"
"QPushButton:hover\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"/*为pressed状态QPushButton设置属性*/\n"
"QPushButton:pressed\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"/*按钮为默认按钮时（不管焦点直接接收键盘回车输入的按钮），一般对话框ok按钮为默认按钮*/\n"
".QPushButton:default\n"
"{\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-style:solid;/*边框类型*/\n"
"    /*用渐变色可以营造光晕边框效果*/\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #64bff0, stop:1 #bae3f7)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #64bff0, stop:1 #bae3f7)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #64bff0, stop:1 #bae3f7)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #64bff0, stop:1 #bae3f7);/*左边框渐变色*/\n"
"}\n"
"    \n"
"/*为focus状态QPushButton设置属性，QPushButtond的子类,如QCommandLinkButton不设置该属性*/\n"
".QPushButton:focus\n"
"{\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-style:solid;/*边框类型*/\n"
"    \n"
"    /*用渐变色可以营造光晕边框效果*/\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #f9b158, stop:1 #ffe189)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #f9b158, stop:1 #ffe189)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f9b158, stop:1 #ffe189)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #f9b158, stop:1 #ffe189);/*左边框渐变色*/\n"
"}\n"
"\n"
"/*为QCommandLinkButton设置通用属性*/\n"
"QCommandLinkButton\n"
"{\n"
"    border: none;/*边框*/\n"
"    background: none;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QCheckBox///////////////////////////////////////////*/\n"
"/*QCheckBox的公用属性设置*/\n"
"QCheckBox\n"
"{\n"
"    spacing:5px;/*指示器与文字之间的距离*/\n"
"    outline:none;/*表示foucs状态时取消虚线框*/\n"
"}\n"
"\n"
"/*QCheckBox指示器subcontrol属性设置*/\n"
"QCheckBox::indicator\n"
"{\n"
"    width:15px;/*设置固定宽度，width height设置的宽高为content区宽高*/\n"
"    height:15px;/*设置固定高度*/\n"
"}\n"
"\n"
"/*QCheckBox指示器选中时属性设置*/\n"
"QCheckBox::indicator:checked\n"
"{\n"
"    image:url(:/qss/icon/checkbox_p.png);/*图片*/\n"
"}\n"
"\n"
"/*QCheckBox指示器未选中时属性设置*/\n"
"QCheckBox::indicator:unchecked\n"
"{\n"
"    image:url(:/qss/icon/checkbox.png);/*图片*/\n"
"}\n"
"\n"
"/*QCheckBox指示器未选中时且hover时属性设置*/\n"
"QCheckBox::indicator:unchecked:hover\n"
"{\n"
"    image:url(:/qss/icon/checkbox_h.png);/*图片*/\n"
"        \n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QRadioButton///////////////////////////////////////////*/\n"
"/*QRadioButton公用属性设置*/\n"
"QRadioButton\n"
"{\n"
"    spacing:5px;/*指示器与文字之间的距离*/\n"
"    outline:none;/*表示foucs状态时取消虚线框*/\n"
"}\n"
"\n"
"/*QRadioButton指示器选中时属性设置*/\n"
"QRadioButton::indicator\n"
"{\n"
"    width:15px;/*设置固定宽度，width height设置的宽高为content区宽高*/\n"
"    height:15px;/*设置固定宽度*/\n"
"}\n"
"\n"
"/*QRadioButton指示器选中时属性设置*/\n"
"QRadioButton::indicator:checked\n"
"{\n"
"    image:url(:/qss/icon/radio_p.png);/**/\n"
"}\n"
"\n"
"/*QRadioButton指示器未选中时属性设置*/\n"
"QRadioButton::indicator:unchecked\n"
"{\n"
"    image:url(:/qss/icon/radio.png);/**/\n"
"}\n"
"\n"
"/*QRadioButton指示器未选中掠过时属性设置*/\n"
"QRadioButton::indicator:unchecked:hover\n"
"{\n"
"    image:url(:/qss/icon/radio_h.png);/**/\n"
"        \n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QLineEdit///////////////////////////////////////////*/\n"
"/*QLineEdit公用属性设置*/\n"
"QLineEdit \n"
"{\n"
"     padding:1px;\n"
"     padding-left:4px;\n"
"    border: 1px solid #aaaaaa;\n"
"    background: white;\n"
"    selection-background-color: #3399ff;\n"
"}\n"
"\n"
"\n"
"/*QLineEdit获得焦点时的属性设置，主要为光晕边框\n"
"这里带了.，所以该属性仅对QLineEdit直接类对象生效，这样做的目的在于，可编辑QTableWidget编辑item时的编辑框不带边框*/\n"
".QLineEdit:focus1\n"
"{\n"
"      padding:0px;/*padding，这里边框为2px为了不引起content尺寸变化padding设置为0*/\n"
"    padding-left:3px;\n"
"    border-width:2px;/*边框宽度*/\n"
"    border-style:solid;/*边框类型*/\n"
"    /*用渐变色可以营造光晕边框效果*/\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #f9b158, stop:1 #ffe189)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #f9b158, stop:1 #ffe189)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #f9b158, stop:1 #ffe189)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #f9b158, stop:1 #ffe189);/*左边框渐变色*/\n"
"}\n"
"\n"
"QLineEdit:read-only\n"
"{\n"
"    color: #787878;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QPlainTextEdit///////////////////////////////////////////*/\n"
"QPlainTextEdit\n"
"{\n"
"    padding:0px;\n"
"    border: 1px solid #aaaaaa;\n"
"    background: white;\n"
"    selection-background-color: #3399ff;\n"
"}\n"
"\n"
"QPlainTextEdit:read-only \n"
"{\n"
"    color: #787878;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QTextEdit///////////////////////////////////////////*/\n"
"QTextEdit\n"
"{\n"
"    padding:0px;\n"
"    border: 1px solid #aaaaaa;\n"
"    background: white;\n"
"    selection-background-color: #3399ff;\n"
"}\n"
" \n"
"\n"
"/*/////////////////////////////////////////////////QComboBox///////////////////////////////////////////*/ \n"
"/*QComboBox设置公用属性*/\n"
"QComboBox\n"
"{\n"
"     border: 1px solid #aaaaaa;/*边框*/\n"
"     padding:2px 18px 2px 3px;/*内边距，有偏移18px为drop-down按钮留出空间，所以subcontrol-origin属性须设为padding*/\n"
"     min-width:36px;/*最小宽度为6em em和px一样为长度单位。em表示对应字体M的宽度。M为大写字母的最大宽度*/\n"
"}\n"
"\n"
"/*QLineEdit获得焦点时的属性设置，设置边框为光晕边框*/\n"
"QComboBox:focus1\n"
"{\n"
"      padding:1px 17px 1px 2px;/*padding，这里边框为2px为了不引起content尺寸变化padding均减1*/\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    border-color:qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #64bff0, stop:1 #bae3f7)/*上边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #64bff0, stop:1 #bae3f7)/*右边框渐变色*/\n"
"      qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #64bff0, stop:1 #bae3f7)/*下边框渐变色*/\n"
"      qlineargradient(x1:1, y1:0, x2:0, y2:0, stop:0 #64bff0, stop:1 #bae3f7);/*左边框渐变色*/\n"
"}\n"
"\n"
"/*设置drop-down按钮上的箭头图片*/\n"
"QComboBox::down-arrow \n"
"{\n"
"    image:url(:/qss/icon/downarrow.png);\n"
"}\n"
"\n"
"/*设置drop-down按钮属性，自定义combox的重头戏。必须设置*/\n"
"QComboBox::drop-down {\n"
"    width:15px;/*drop-down按钮宽度*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*drop-down按钮渐变背景色*/\n"
"    subcontrol-origin: padding;/*drop-down按钮绘制位置依据父控件设置的padding决定*/\n"
"    subcontrol-position: right top;/*drop-down按钮相对父控件位置*/\n"
"    border-left:1px solid #aaaaaa;/*drop-down左边框*/\n"
"}\n"
"\n"
"/*设置QComboBox的：下拉时的视图属性。注意这不是设置的视图项，而是视图项主城的视图\n"
"子孙窗口部件，用空格隔开。*/\n"
"QComboBox QAbstractItemView \n"
"{\n"
"     border: 1px solid #aaaaaa;/*边框*/\n"
"     selection-background-color: #73c5f1;/*选中背景*/\n"
"     outline:none;/*去掉选中时的虚线框*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QGroupBox///////////////////////////////////////////*/ \n"
"/*QGroupBox公用属性设置*/\n"
" QGroupBox {\n"
"     background: none;/*背景透明*/\n"
"     border: 1px solid #aaaaaa;/*边框*/\n"
"     border-radius: 5px;/*边框圆角*/\n"
"     margin-top: 2ex; /* 为title绘制留出空间，以下title子控制器的subcontrol-origin设置为margin */\n"
" }\n"
"\n"
"/*QGroupBox title子控制器属性设置*/\n"
"QGroupBox::title \n"
"{\n"
"    color:#3399ff;/*文本颜色*/\n"
"     left:10px;/*子控制器相对于父控件的精确定位*/\n"
"    subcontrol-origin: margin;/*子控制器绘制起始区域*/\n"
"    subcontrol-position: top left; /*子控制器于父控件的相对位置*/\n"
"    padding: 0px 2px;/*title文字左右padding设置使边框线条与title文字有间隔距离*/\n"
"    background: none;/*背景透明*/\n"
" }\n"
"\n"
"/*/////////////////////////////////////////////////QProgressBar///////////////////////////////////////////*/ \n"
"/*QProgressBar公用属性设置*/\n"
"QProgressBar \n"
"{\n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    background: white;/*qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eeeeee, stop:1 #ffffff);渐变背景*/\n"
"    border-radius: 4px;/*边框圆角*/\n"
"    text-align:center;/*文本对齐*/\n"
"}\n"
"\n"
"/*chunk子控制器，指进度条内一块块依次向右的进度小块*/\n"
"QProgressBar::chunk \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #73c5f1, stop:0.6 #bde4f8, stop:1 #73c5f1); /*进度小块背景*/\n"
"    width: 6px;/*进度小块宽度*/\n"
"    margin: 0.5px;/*进度小块margin设置为0.5px以上可以隔开进度小块。隔开距离为2*margin 。设置为0.5以下进度小块连在一起*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QSlider///////////////////////////////////////////*/ \n"
"/*QSlider水平凹槽属性设置，未设置背景因为它反正会被add-page subControl覆盖*/\n"
"QSlider::groove:horizontal \n"
"{\n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    height: 6px; /*水平凹槽高度*/\n"
"}\n"
"\n"
"/*QSlider水平滑块属性设置*/\n"
"QSlider::handle:horizontal \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:1 #666666, stop:0.5 #dddddd);/*渐变背景*/\n"
"    border: 1px solid #5c5c5c;/*边框*/\n"
"    width: 6px;/*滑块宽度*/\n"
"    margin: -6px 0;/*通过设置margin上下margin为-6px，使得滑块高度比凹槽高度高12px。*/\n"
"    border-radius: 4px;/*圆角边框*/\n"
" }\n"
"\n"
"/*通过add-page subControl设置未划过部分的背景*/\n"
"QSlider::add-page:horizontal \n"
"{\n"
"    border: 1px solid #aaaaaa;\n"
"    background: white;/*qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eeeeee, stop:1 #ffffff);*/\n"
"}\n"
"\n"
"/*通过sub-page subControl设置划过部分的背景*/\n"
"QSlider::sub-page:horizontal \n"
"{\n"
"    border: 1px solid #aaaaaa;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #73c5f1, stop:0.6 #bde4f8, stop:1 #73c5f1); \n"
"}\n"
" \n"
"/*垂直滑动条：大同小异*/\n"
"QSlider::groove:vertical \n"
"{\n"
"   border: 1px solid #aaaaaa;\n"
"   width: 6px; \n"
"}\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:1 #666666, stop:0.4 #dddddd);/*渐变背景*/\n"
"    border: 1px solid #5c5c5c;\n"
"    height: 6px;\n"
"    margin: 0px -6px;\n"
"    border-radius: 4px;\n"
"}\n"
" \n"
"QSlider::add-page:vertical \n"
"{\n"
"    border: 1px solid #aaaaaa;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #73c5f1, stop:0.6 #bde4f8, stop:1 #73c5f1); \n"
"}\n"
"\n"
"QSlider::sub-page:vertical \n"
"{\n"
"    border: 1px solid #aaaaaa;\n"
"    background: white;/*qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #eeeeee, stop:1 #ffffff);*/\n"
"}\n"
"\n"
"\n"
"/*/////////////////////////////////////////////////QScrollBar///////////////////////////////////////////*/ \n"
"/*水平滚动条公用属性设置*/\n"
"QScrollBar:horizontal\n"
"{\n"
"    border-top: 1px solid #aaaaaa;/*边框*/\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);渐变背景，也是滑轨背景*/\n"
"    background:white;\n"
"    height: 16px;/*水平滚动条高度*/\n"
"    margin: 0px 16px 0 16px;/*水平滚动条margin，左右留出空间给add-line按钮和sub-line按钮*/\n"
"}\n"
"\n"
"/*水平滚动条滑块公用属性设置*/\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #73c5f1, stop:0.6 #bde4f8, stop:1 #73c5f1);背景*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    min-width: 20px;/*最小宽度，滑块宽度自动调整但须设置一个最小宽度*/\n"
"    border-radius: 0px;/**/\n"
"    border-left:1px solid #aaaaaa;\n"
"    border-right:1px solid #aaaaaa;\n"
"}\n"
"\n"
"/*水平滚动条滑块被掠过时*/\n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #90d9fe, stop:0.6 #e2f3fc, stop:1 #90d9fe);渐变背景*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.2 #eeeeee, stop:1 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"/*水平滚动条滑块被按压时*/\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:0, y2:1,  stop:0 #60c8fd, stop:0.6 #bde4f8, stop:1 #60c8fd);渐变背景*/\n"
"   background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"}\n"
"\n"
"/*水平滚动条sub-line（增加一行）按钮*/\n"
"QScrollBar::add-line:horizontal \n"
"{\n"
"    border-top: 1px solid #aaaaaa;/*边框*/\n"
"    border-left: 1px solid #aaaaaa;/*边框*/\n"
"    border-right: 1px solid #aaaaaa;/*边框*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景*/\n"
"    width: 16px;/*宽度，跟父控件margin匹配*/\n"
"    subcontrol-position: right;/*sub-line按钮相对于父控件位置设置*/\n"
"    subcontrol-origin: margin;/*sub-line按钮绘制空间，之前父控件设置了margin为sub-line留出了控件*/\n"
"}\n"
" \n"
"/*水平滚动条add-line（增加一行）按钮被掠过时*/\n"
"QScrollBar::add-line:horizontal:hover\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.4 #ffffff, stop:1 #eeeeee);/*渐变背景*/\n"
"}\n"
" \n"
"/*水平滚动条add-line（增加一行）按钮被按压时*/\n"
"QScrollBar::add-line:horizontal:pressed\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.4 #eeeeee);/*渐变背景*/\n"
"}\n"
"\n"
"/*水平滚动条sub-line（减少一行）按钮*/\n"
"QScrollBar::sub-line:horizontal \n"
"{\n"
"    border-top: 1px solid #aaaaaa;/*边框*/\n"
"    border-right: 1px solid #aaaaaa;/*边框*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景*/\n"
"    width: 16px;/*宽度，跟父控件margin匹配*/\n"
"    subcontrol-position: left;/*sub-line按钮相对于父控件位置设置*/\n"
"    subcontrol-origin: margin;/*sub-line按钮绘制空间，之前父控件设置了margin为sub-line留出了控件*/\n"
"}\n"
"\n"
"/*水平滚动条sub-line（减少一行）按钮hover时*/\n"
"QScrollBar::sub-line:horizontal:hover\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0.4 #ffffff, stop:1 #eeeeee);/*渐变背景*/\n"
"}\n"
"\n"
"/*水平滚动条sub-line（减少一行）按钮被按压时*/\n"
"QScrollBar::sub-line:horizontal:pressed\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.4 #eeeeee);/*渐变背景*/\n"
"}\n"
"\n"
"/*水平滚动条左箭头设置图像（在add-line中居中显示）*/\n"
"QScrollBar:left-arrow:horizontal\n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_left_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*水平滚动条右箭头设置图像（在sub-line中居中显示）*/\n"
"QScrollBar::right-arrow:horizontal \n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_right_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*水平滚动条add-page,sub-page指单击滑轨时滚动一页。可以为add-page,sub-page设置hover,pressed的背景 */\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"     background: none;/*不设置add-page,sub-page背景*/\n"
"}\n"
"\n"
"\n"
"/*垂直滚动条，大同小异*/\n"
"QScrollBar:vertical\n"
"{\n"
"    border-left: 1px solid #aaaaaa;\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);*/\n"
"    background:white;\n"
"    width: 16px;\n"
"    margin: 16px 0px 16px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #73c5f1, stop:0.6 #bde4f8, stop:1 #73c5f1);渐变背景色*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    min-height: 20px;\n"
"    border-radius: 0px;\n"
"    border-top:1px solid #aaaaaa;\n"
"    border-bottom:1px solid #aaaaaa;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #90d9fe, stop:0.6 #e2f3fc, stop:1 #90d9fe);渐变背景*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0.2 #eeeeee, stop:1 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"    /*background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #60c8fd, stop:0.6 #bde4f8, stop:1 #60c8fd);渐变背景色*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical \n"
"{\n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);\n"
"    height: 16px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical:hover\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0.4 #ffffff, stop:1 #eeeeee);\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical:pressed\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.4 #eeeeee);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical \n"
"{\n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);\n"
"    height: 16px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical:hover\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0.4 #ffffff, stop:1 #eeeeee);\n"
"}\n"
" \n"
"QScrollBar::sub-line:vertical:pressed\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #ffffff, stop:0.4 #eeeeee);\n"
"}\n"
" \n"
"QScrollBar::down-arrow:vertical\n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"    background: none;\n"
"}\n"
"\n"
"/*\n"
"一种更为简洁的滚动条\n"
"QScrollBar:horizontal\n"
"{\n"
"    background: #f2f2f2;\n"
"    height: 12px;\n"
"}\n"
"QScrollBar::handle:horizontal \n"
"{\n"
"    background: #dddddd;\n"
"    min-width: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background: #d0d0d0;\n"
"}\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"    background: #d0d0d0;\n"
"}\n"
" \n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal \n"
"{\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal \n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar:vertical\n"
"{\n"
"    background: #f2f2f2;\n"
"    width: 12px;\n"
"}\n"
"QScrollBar::handle:vertical \n"
"{\n"
"    background: #dddddd;\n"
"    min-height: 20px;\n"
"    border-radius: 6px;\n"
"}\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background: #d0d0d0;\n"
"}\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"    background: #d0d0d0;\n"
"}\n"
" \n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical \n"
"{\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical \n"
"{\n"
"     background: none;\n"
"}\n"
"*/\n"
"\n"
"/*/////////////////////////////////////////////////QTabWidget///////////////////////////////////////////*/ \n"
"/*QTabWidget由子控制器pane和tab-bar组成。pane为tab页所在区域，tab-bar为tab标签栏所在区域*/\n"
"/*QTabWidget pane子控制器属性设置*/\n"
"QTabWidget::pane \n"
"{\n"
"    border: 0px solid #aaaaaa; /*tab有边框pane就不要边框了*/\n"
"    margin-top:-1px;/*设置margin-top为-1是为了让tab-bar遮掉pane的上边框*/\n"
"}\n"
"\n"
"/*QTabWidget tab-bar子控制器属性设置*/\n"
"QTabWidget::tab-bar \n"
"{\n"
"    alignment: center; /*left表示子控制器距父控件左边的距离定位*/\n"
"}\n"
"\n"
"/*tab-bar子控制器（tab标签栏）又由tab标签组成，子控制器tab表示tab标签*/\n"
"QTabBar::tab \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #dddddd);/*渐变背景色*/\n"
"    border-left: 1px solid #aaaaaa;/*边框，不设置标签底部边框*/\n"
"    border-right: 1px solid #aaaaaa;/**/\n"
"    border-top: 1px solid #aaaaaa;/**/\n"
"    border-top-left-radius: 6px;/**/\n"
"    border-top-right-radius: 6px;/**/\n"
"    min-width: 18ex;/**/\n"
"    padding: 4px;/**/\n"
"}\n"
"\n"
"/*tab标签被选中或掠过时*/\n"
"QTabBar::tab:selected, QTabBar::tab:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"}\n"
"\n"
"/*tab标签被选中时*/\n"
"QTabBar::tab:selected\n"
"{\n"
"    border-bottom: 3px solid #73c5f1;/*设置底部边框*/\n"
"    margin-left: -4px;/*设置margin-top为-4px是为了扩大选中标签宽度，使得选中标签宽度大于未选中标签*/\n"
"    margin-right: -4px;/**/\n"
"}\n"
"\n"
"/*tab标签未被选中时*/\n"
"QTabBar::tab:!selected \n"
"{\n"
"    border-bottom: 1px solid #aaaaaa;/*设置底部边框*/\n"
"    margin-top: 2px;/*设置margin-top为了压缩标签大小，使得未选中标签高度小于选中标签*/\n"
"}\n"
"\n"
"/*第一个tab标签被选中时*/\n"
"QTabBar::tab:first:selected \n"
"{\n"
"    margin-left: 0px; /*左边不扩大宽度*/\n"
"}\n"
"\n"
"/*最后一个tab标签被选中时*/\n"
"QTabBar::tab:last:selected \n"
"{\n"
"    margin-right: 0px;/*右边不扩大宽度*/\n"
"}\n"
"\n"
"/*只有一个tab标签时*/\n"
"QTabBar::tab:only-one \n"
"{\n"
"    margin: 0px;/*不使用margin对标签大小作改变*/\n"
"}\n"
"\n"
"/*QTabBar上标签过多时出现的左右箭头QToolButton按钮属性设置*/\n"
"QTabBar QToolButton \n"
"{ \n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/*QTabBar上标签过多时出现的左右箭头按钮箭头图片*/\n"
"QTabBar QToolButton::right-arrow \n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_right_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*QTabBar上标签过多时出现的左右箭头按钮箭头图片*/\n"
"QTabBar QToolButton::left-arrow \n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_left_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"\n"
"/*/////////////////////////////////////////////////QCalendarWidget日历控件///////////////////////////////////////////*/ \n"
"QCalendarWidget QToolButton\n"
"{\n"
"    color:Black;\n"
"}\n"
"\n"
"/*QCalendarWidget上左右箭头按钮箭头图片*/\n"
"QCalendarWidget QToolButton::right-arrow \n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_right_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*QCalendarWidget上左右箭头按钮箭头图片*/\n"
"QCalendarWidget QToolButton::left-arrow \n"
"{\n"
"    image:url(:/qss/icon/hor_scroll_left_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QListView/QListWidget///////////////////////////////////////////*/\n"
"/*QListView公用属性设置*/ \n"
"QListView\n"
"{\n"
"    border:1px solid #aaaaaa;/*边框*/\n"
"    selection-background-color: #73c5f1;/*选中背景*/\n"
"    alternate-background-color:#e9e9e9;/*交替行背景色，代码中设置了交替行背景设有效时生效*/\n"
"    outline:none;/*去掉选中时的虚线框*/\n"
"}\n"
"\n"
"QListView::item \n"
"{\n"
"    min-height:24px;/*调整项高度*/\n"
"    margin-left:40px;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QTableView/QTableWidget///////////////////////////////////////////*/ \n"
"/*QTableView公用属性设置*/\n"
"QTableView\n"
"{\n"
"    border:1px solid #aaaaaa;/*边框*/\n"
"    background:#ffffff;/*背景*/\n"
"    selection-background-color: #73c5f1;/*选中背景*/\n"
"    alternate-background-color:#e9e9e9;/*交替行背景色，代码中设置了交替行背景设有效时生效*/\n"
"}\n"
"\n"
"/*QTableView的CornerButton区域设置*/\n"
"QTableView QTableCornerButton::section\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    border: 1px outset #aaaaaa;/*边框 outset类型边框指右底边框比左上边框颜色深，可参见w3c border-style属性*/\n"
"}\n"
"\n"
"/*QTableView表头设置，设置表头所有位置的背景，而不是仅仅为section部分，包括垂直和水平表头*/\n"
"QTableView QHeaderView\n"
"{\n"
"    background: #eeeeee;/*QHeaderView背景色*/\n"
"}\n"
"\n"
"/*QTableView表头section部分设置，包括垂直和水平表头*/\n"
"QTableView QHeaderView::section\n"
"{\n"
"     background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"     border: 1px outset #aaaaaa;/**/\n"
"     padding:4px;/*调整表头高度*/\n"
"}\n"
"\n"
"QTableView::item \n"
"{\n"
"    min-height:24px;/*调整项高度*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QTreeView/QTreeWidget///////////////////////////////////////////*/ \n"
"/*QTreeView公用属性设置*/\n"
"QTreeView\n"
"{\n"
"    border:1px solid #aaaaaa;/*边框*/\n"
"    show-decoration-selected: 1;\n"
"    background:#ffffff;/*背景*/\n"
"    selection-background-color: #73c5f1;/*选中背景*/\n"
"    alternate-background-color:#e9e9e9;/*交替行背景色，代码中设置了交替行背景设有效时生效*/\n"
"}\n"
"\n"
"/*QTreeView表头设置，设置表头所有位置的背景，而不是仅仅为section部分，包括垂直和水平表头*/\n"
"QTreeView QHeaderView\n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"}\n"
"\n"
"/*QTreeView表头section部分设置，包括垂直和水平表头*/\n"
"QTreeView QHeaderView::section\n"
"{\n"
"     background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"     border: 1px outset #aaaaaa;/**/\n"
"     padding:4px;/*调整表头高度*/\n"
"}\n"
"\n"
"/*QTreeView item子控制器属性设置*/\n"
"QTreeView::item \n"
"{\n"
"    min-height:30px;/*调整项高度*/\n"
"}\n"
"\n"
"/*QTreeView item子控制器掠过时属性设置*/\n"
"QTreeView::item:hover \n"
"{\n"
"    background: #c5e7f9;\n"
"}\n"
"\n"
"/*QTreeView item子控制器选中时属性设置*/\n"
"QTreeView::item:selected \n"
"{\n"
"    border: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"/*QTreeView item子控制器选中且有焦点（此时字体颜色为白）时属性设置*/\n"
"QTreeView::item:selected:active\n"
"{\n"
"    background: #73c5f1;\n"
"}\n"
"\n"
"/*QTreeView item子控制器选中且无焦点（此时字体颜色为黑）时属性设置*/\n"
"QTreeView::item:selected:!active \n"
"{\n"
"    background: #73c5f1;\n"
"}\n"
" \n"
"/*branch没有合适的素材，暂时先不定制\n"
" QTreeView::branch {\n"
"         background: palette(base);\n"
" }\n"
" QTreeView::branch:has-siblings:!adjoins-item {\n"
"         background: cyan;\n"
" }\n"
" QTreeView::branch:has-siblings:adjoins-item {\n"
"         background: red;\n"
" }\n"
" QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"         background: blue;\n"
" }\n"
" QTreeView::branch:closed:has-children:has-siblings {\n"
"         background: pink;\n"
" }\n"
" QTreeView::branch:has-children:!has-siblings:closed {\n"
"         background: gray;\n"
" }\n"
" QTreeView::branch:open:has-children:has-siblings {\n"
"         background: magenta;\n"
" }\n"
" QTreeView::branch:open:has-children:!has-siblings {\n"
"         background: green;\n"
" }\n"
" QTreeView::branch:has-siblings:!adjoins-item {\n"
"     border-image: url(vline.png) 0;\n"
" }\n"
" QTreeView::branch:has-siblings:adjoins-item {\n"
"     border-image: url(branch-more.png) 0;\n"
" }\n"
" QTreeView::branch:!has-children:!has-siblings:adjoins-item {\n"
"     border-image: url(branch-end.png) 0;\n"
" }\n"
" QTreeView::branch:has-children:!has-siblings:closed,\n"
" QTreeView::branch:closed:has-children:has-siblings {\n"
"         border-image: none;\n"
"         image: url(branch-closed.png);\n"
" }\n"
" QTreeView::branch:open:has-children:!has-siblings,\n"
" QTreeView::branch:open:has-children:has-siblings  {\n"
"         border-image: none;\n"
"         image: url(branch-open.png);\n"
" }\n"
"*/\n"
"\n"
"/*/////////////////////////////////////////////////QMenuBar///////////////////////////////////////////*/ \n"
"/*菜单栏公用属性设置*/\n"
"QMenuBar \n"
"{\n"
"    border-bottom:1px solid #aaaaaa;\n"
"    /*background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0.2 #dddddd, stop:1 #ffffff);渐变背景色*/\n"
"    background:#f2f2f2;\n"
"}\n"
"\n"
"/*菜单栏item子控制器（菜单项）属性设置*/\n"
"QMenuBar::item \n"
"{\n"
"    spacing: 3px; /* 设置菜单项之间空隙*/\n"
"    padding: 2px 10px;/*通过padding设置菜单项之间空隙和菜单栏高度*/\n"
"    background: transparent;/* 菜单项目本身背景透明*/\n"
"    border-radius: 1px;/*菜单项的圆角边框 */\n"
"}\n"
"\n"
"/* 菜单栏item子控制器（菜单项）被选中时（菜单中的被选中即为被掠过，此时不弹出菜单项目列表） */\n"
"QMenuBar::item:selected \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #cccccc);/*渐变背景色*/\n"
"}\n"
"\n"
"/* 菜单栏item子控制器（菜单项）被按压时（此时弹出菜单项目列表） */\n"
"QMenuBar::item:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #dddddd, stop:0.8 #bbbbbb);/*渐变背景色*/\n"
"}\n"
"\n"
"\n"
"/*/////////////////////////////////////////////////QMenu///////////////////////////////////////////*/ \n"
"/*菜单项目列表(就是那个下拉列表)属性设置*/\n"
"QMenu \n"
"{\n"
"     background-color: white; /* 背景色 */\n"
"     border: 1px solid #aaaaaa;/* 边框 */\n"
" }\n"
"\n"
"/*菜单项目列表item子控制器（菜单项目列表中菜单项目，注意item子控制器不包括图表和指示器，所以该子控制器影响的只有）属性设置*/\n"
"QMenu::item \n"
"{\n"
"     background-color: transparent;/*背景色透明*/\n"
"     padding:4px 26px 4px 26px;/*通过菜单项目padding属性调整菜单项目中文字位置*/\n"
" }\n"
"\n"
"/*菜单项目列表item子控制器被选中（菜单中的被选中即为被掠过）时属性设置*/\n"
"QMenu::item:selected \n"
"{\n"
"    background-color: #73c5f1;/*设置背景色*/\n"
"}\n"
"\n"
"/*菜单项目列表separator子控制器属性设置，即对菜单项目列表中的分隔条设置*/\n"
"QMenu::separator \n"
"{\n"
"   height: 1px;\n"
"   background: #AAAAAA;\n"
"   margin-left: 25px;/*左右留空*/\n"
"   margin-right: 5px;\n"
"}\n"
"\n"
"/*菜单项目列表right-arrow子控制器属性设置，即对菜单项目列表中的二级菜单的箭头设置*/\n"
"QMenu::right-arrow \n"
"{\n"
"    right:5px;/*调整箭头位置*/\n"
"    image:url(:/qss/icon/hor_scroll_right_arrow.png);/*箭头图像*/\n"
"}\n"
"\n"
"/*菜单项目列表icon子控制器属性设置，即对菜单项目中图标的设置，但好像很多属性都不起作用如边框、背景、大小等，何解？*/\n"
"QMenu::icon \n"
"{ \n"
"    position:relative;/*position指示：调整subcontrol位置的属性top left bottom right设置距离为相对subcontrol自身（relative）还是相对父控件（absolut）。默认为relative*/\n"
"    left: 5px;/*调整图表位置*/\n"
"}\n"
"\n"
"\n"
"/*菜单项目列表indicator子控制器属性设置，即对菜单项目中指示器（包括checkable menu item前面的复选框、\n"
"exclusive checkable menu item前面的那个单选框）的设置，但好像很多属性都不起作用如边框、背景、大小等，何解？*/\n"
"QMenu::indicator \n"
"{\n"
"    position:relative;/*position指示：调整subcontrol位置的属性top left bottom right设置距离为相对subcontrol自身（relative）还是相对父控件（absolut）。默认为relative*/\n"
"    left: 5px;/*调整指示器位置*/\n"
"}\n"
"\n"
"/*菜单项目非排他指示器即复选框为选中时的属性设置*/\n"
"QMenu::indicator:non-exclusive:unchecked \n"
"{\n"
"    image: url(:/qss/icon/checkbox.png);\n"
"}\n"
"\n"
"/*菜单项目非排他指示器即复选框为选中被掠过时的属性设置*/\n"
"QMenu::indicator:non-exclusive:unchecked:selected \n"
"{\n"
"    image: url(:/qss/icon/checkbox_h.png);\n"
"}\n"
"\n"
"/*菜单项目非排他指示器即复选框为选中时的属性设置*/\n"
"QMenu::indicator:non-exclusive:checked \n"
"{\n"
"    image: url(:/qss/icon/checkbox_p.png);\n"
"}\n"
"\n"
"/*菜单项目非排他指示器即复选框为选中被掠过时的属性设置*/\n"
"QMenu::indicator:non-exclusive:checked:selected \n"
"{\n"
"    image: url(:/qss/icon/checkbox_p.png);\n"
"}\n"
" \n"
" \n"
"/* 菜单项目排他指示器属性设置，大同小异 */\n"
"QMenu::indicator:exclusive:unchecked \n"
"{\n"
"    image: url(:/qss/icon/radio.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:selected \n"
"{\n"
"    image: url(:/qss/icon/radio_h.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked \n"
"{\n"
"    image: url(:/qss/icon/radio_p.png);\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:selected \n"
"{\n"
"    image: url(:/qss/icon/radio_p.png);\n"
"}\n"
"\n"
"\n"
"/*/////////////////////////////////////////////////QToolButton///////////////////////////////////////////*/ \n"
"/*QToolButton:工具栏上按钮或单独的工具按钮（单独工具按钮可弹出popupmenu）*/\n"
"/**/\n"
"/*QToolButton公用属性设置*/\n"
"QToolButton \n"
"{ \n"
"    min-height:20px;/*最小宽度*/\n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    border-radius: 4px;/*QToolButton与QPushButton基本一致，但这里设置的边框圆角不一致*/\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    outline:none;/*表示foucs状态时取消虚线框*/\n"
"}\n"
"\n"
"/*QToolButton类型为DelayPopup时为menu-indicator子控制器留出空间\n"
"DelayPopup表示持续按压按钮可弹出菜单*/\n"
"QToolButton[popupMode=\"0\"] \n"
"{ \n"
"    padding-right: 4px; /*用padding留出空间，初始subcontrol-origin属性要为padding*/\n"
"}\n"
"\n"
"/*QToolButton类型为MenuButtonPopup时为menu-button子控制器留出空间\n"
"MenuButtonPopup表示点击menu-button子控制器可弹出菜单*/\n"
"QToolButton[popupMode=\"1\"] \n"
"{ \n"
"    padding-right: 18px; /*用padding留出空间，初始subcontrol-origin属性要为padding*/\n"
"}\n"
"\n"
"/*QToolButton类型为InstantPopup时为menu-indicator子控制器留出空间\n"
"MenuButtonPopup表示点击QToolButton即可立即弹出菜单，Instant表示立即意思*/\n"
"QToolButton[popupMode=\"2\"] \n"
"{ \n"
"    padding-right: 4px;/*用padding留出空间，初始subcontrol-origin属性要为padding*/\n"
"}\n"
"\n"
"/*QToolButton pressed伪状态时属性设置，注意hover伪状态设置一定要在pressed伪状态之前！！！！！！！！！！*/\n"
"QToolButton:hover  \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"/*QToolButton pressed伪状态时属性设置，注意hover伪状态设置一定要在pressed伪状态之前！！！！！！！！！！*/\n"
"QToolButton:pressed  \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"/*QToolButton menu-button子控制器属性设置\n"
"menu-button子控制器仅对MenuButtonPopup类型QToolButton生效*/\n"
"QToolButton::menu-button \n"
"{\n"
"    border-left: 1px solid #aaaaaa;/*设置左边边框即可*/\n"
"    border-top-right-radius: 4px;/*设置右上边框圆角，与QToolButton自身圆角保持一致*/\n"
"    border-bottom-right-radius: 4px;/*设置右小边框圆角，与QToolButton自身圆角保持一致*/\n"
"    width: 16px;/*设置menu-button宽度，注意与QToolButton的padding-right属性值匹配*/\n"
"}\n"
"\n"
"/*QToolButton menu-arrow子控制器属性设置\n"
"menu-arrow子控制器仅对MenuButtonPopup类型QToolButton生效，它为menu-button箭头*/\n"
"QToolButton::menu-arrow \n"
"{\n"
"    position:relative;/*position指示：调整subcontrol位置的属性top left bottom right设置距离为相对subcontrol自身（relative）还是相对父控件（absolut）。默认为relative*/\n"
"    top: 1px; /*顶部相对偏移1px,调整menu-arrow相对父控件位置*/\n"
"    right: 1px; /*右边相对偏移1px,调整menu-arrow相对父控件位置*/\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);/*箭头图片*/\n"
"}\n"
"\n"
"/*QToolButton menu-arrow子控制器在菜单展开式的属性设置\n"
"menu-arrow子控制器仅对MenuButtonPopup类型QToolButton生效，它为menu-button箭头*/\n"
"QToolButton::menu-arrow:open \n"
"{\n"
"    top: 2px; /*顶部偏移1px,让箭头有下沉效果*/\n"
"}\n"
"\n"
"/*QToolButton menu-indicator子控制器属性设置\n"
"menu-indicator子控制器仅对MenuButtonPopup和InstantPopup类型QToolButton生效，它表示按钮拥有菜单的指示*/\n"
"QToolButton::menu-indicator \n"
"{ \n"
"      image:url(:/qss/icon/ver_scroll_bottom_arrow.png);/*箭头图片*/\n"
"      width:7px;/*menu-indicator宽度*/\n"
"      height:7px;/*menu-indicator高度*/\n"
"      padding:0px 2px;/*调整menu-indicator位置*/\n"
"}\n"
" \n"
"/*/////////////////////////////////////////////////QToolBar///////////////////////////////////////////*/ \n"
"/*QToolBar公用属性设置*/   \n"
"QToolBar \n"
"{\n"
"    spacing:2px;/*调整工具栏按钮间距离*/\n"
"    background:#f2f2f2;/*设置背景色与主窗口背景一致，这样在拖动时就不会露出原来背景色*/   \n"
"}\n"
"\n"
"/*QToolBar handle子控制器（就是那个工具栏拖动按钮）属性设置 */  \n"
"QToolBar::handle \n"
"{\n"
"    /*保存默认即可*/\n"
"}\n"
"\n"
"/*QToolBar separator子控制器（就是工具栏之间风格条）属性设置 */  \n"
"QToolBar::separator \n"
"{\n"
"    /*保存默认即可*/\n"
"}\n"
"\n"
"/*由于QToolButton的属性对QToolBar上button属性的影响不知道怎么分离，\n"
"所以QToolBar上按钮效果要完全自己定制，其实qt本身实现的XP系统上玻璃覆盖效果不错*/\n"
"/*QToolBar上按钮属性设置*/\n"
"QToolBar QToolButton\n"
"{\n"
"    margin-bottom:2px;/*调整按钮大小，防止QToolButton hover时遮住QToolBar自身边框*/\n"
"    border: none;/*去掉边框*/\n"
"    background:transparent;/*设置normal状态下背景色为透明色*/\n"
"    border-radius: 4px;/*边框圆角*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QToolTip///////////////////////////////////////////*/ \n"
"/*QToolTip(提示条)公用属性设置*/   \n"
"QToolTip \n"
"{\n"
"    /*background:#f4f4f4;*/\n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    padding: 1px;/*调整大小*/\n"
"    border-radius: 0px;/*边框圆角*/\n"
"    background:#fafafa;\n"
"    opacity: 240;/*不透明度，255时不透明*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QSpinBox///////////////////////////////////////////*/ \n"
"QSpinBox\n"
"{\n"
"    min-height:20px;\n"
"    padding-right: 15px; \n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"     min-width:1em;/*最小宽度为6em em和px一样为长度单位。em表示对应字体M的宽度。M为大写字母的最大宽度*/\n"
"     background:white;\n"
"}\n"
"\n"
"QSpinBox::up-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QSpinBox::up-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled, QSpinBox::up-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 0px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"QSpinBox::down-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QSpinBox::down-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled,\n"
"QSpinBox::down-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 0px solid #dddddd;/*边框*/\n"
"}\n"
" \n"
" \n"
"/*/////////////////////////////////////////////////QDoubleSpinBox///////////////////////////////////////////*/ \n"
"QDoubleSpinBox\n"
"{\n"
"    min-height:20px;\n"
"    padding-right: 15px; \n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"     min-width:4em;/*最小宽度为6em em和px一样为长度单位。em表示对应字体M的宽度。M为大写字母的最大宽度*/\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDoubleSpinBox::up-arrow:disabled, \n"
"QSpinBox::up-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow {\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-arrow:disabled,\n"
"QDoubleSpinBox::down-arrow:off \n"
"{ \n"
"     background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QTimeEdit///////////////////////////////////////////*/ \n"
"QTimeEdit\n"
"{\n"
"    min-height:20px;\n"
"    padding-right: 15px; \n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"     min-width:8em;/*最小宽度为6em em和px一样为长度单位。em表示对应字体M的宽度。M为大写字母的最大宽度*/\n"
"}\n"
"\n"
"QTimeEdit::up-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QTimeEdit::up-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QTimeEdit::up-button:pressed \n"
"{\n"
"   background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QTimeEdit::up-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QTimeEdit::up-arrow:disabled, \n"
"QTimeEdit::up-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"QTimeEdit::down-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QTimeEdit::down-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QTimeEdit::down-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QTimeEdit::down-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QTimeEdit::down-arrow:disabled,\n"
"QTimeEdit::down-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"\n"
"/*/////////////////////////////////////////////////QDateEdit///////////////////////////////////////////*/ \n"
"QDateEdit\n"
"{\n"
"    min-height:20px;\n"
"    padding-right: 15px; \n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"     min-width:10em;/*最小宽度为6em em和px一样为长度单位。em表示对应字体M的宽度。M为大写字母的最大宽度*/\n"
"}\n"
"\n"
"QDateEdit::up-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDateEdit::up-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateEdit::up-button:pressed \n"
"{\n"
"   background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateEdit::up-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDateEdit::up-arrow:disabled, \n"
"QDateEdit::up-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"QDateEdit::down-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDateEdit::down-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QTimeEdit::down-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateEdit::down-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:disabled,\n"
"QDateEdit::down-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QDateTimeEdit///////////////////////////////////////////*/ \n"
"QDateTimeEdit\n"
"{\n"
"    min-height:20px;\n"
"    padding-right: 15px; \n"
"    border: 1px solid #aaaaaa;/*边框*/\n"
"    background:white;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right; /* position at the top right corner */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-bottom: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateTimeEdit::up-button:pressed \n"
"{\n"
"   background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_top_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDateTimeEdit::up-arrow:disabled, \n"
"QDateTimeEdit::up-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"QDateTimeEdit::down-button \n"
"{\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right; \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #eeeeee);/*渐变背景色*/\n"
"    width: 15px; \n"
"    border-left: 1px solid #aaaaaa;\n"
"    border-top: 0px solid #aaaaaa;\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:hover \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #eeeeee, stop:0.8 #ffffff);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateTimeEdit::down-button:pressed \n"
"{\n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.8 #dddddd);/*渐变背景色*/\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow \n"
"{\n"
"    image:url(:/qss/icon/ver_scroll_bottom_arrow.png);\n"
"    width: 9px;\n"
"    height: 9px;\n"
"}\n"
"\n"
"QDateTimeEdit::down-arrow:disabled,\n"
"QDateTimeEdit::down-arrow:off \n"
"{ \n"
"    background: qlineargradient(x1:0, y1:1, x2:0, y2:0, stop:0 #ffffff, stop:0.6 #eeeeee);/*渐变背景色*/\n"
"    border: 1px solid #dddddd;/*边框*/\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QGraphicsView///////////////////////////////////////////*/ \n"
"QGraphicsView\n"
"{\n"
"    border:none;\n"
"}\n"
"/*/////////////////////////////////////////////////QSizeGrip///////////////////////////////////////////*/ \n"
"QSizeGrip\n"
"{\n"
"    image: url(:/qss/icon/sizegrip.png);\n"
"    width: 15px;\n"
"    height: 15px;\n"
" }\n"
"\n"
"/*/////////////////////////////////////////////////QDockWidget///////////////////////////////////////////*/ \n"
"QDockWidget\n"
"{\n"
"    border: 1px solid #aaaaaa;\n"
"    background: #f2f2f2;\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    text-align: left; /* align the text to the left */\n"
"    background: #f0f0f0;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border-bottom:1 solid #aaaaaa;\n"
"}\n"
"\n"
"QMainWindow::separator\n"
"{\n"
"    width:0px;\n"
"    height:0px;\n"
"    border-width: 1px;\n"
"    border-color:#f2f2f2 #f2f2f2 #aaaaaa #aaaaaa ;\n"
"    border-style:solid;\n"
"}\n"
"\n"
"/*/////////////////////////////////////////////////QLCDNumber///////////////////////////////////////////*/ \n"
"QLCDNumber\n"
"{\n"
"    /*background:white;*/\n"
"}")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 981, 531))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(560, 390, 90, 31))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 390, 90, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(50, 390, 90, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(210, 360, 401, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab)
        self.pushButton_8.setGeometry(QtCore.QRect(430, 390, 90, 31))
        self.pushButton_8.setObjectName("pushButton_8")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(110, 40, 691, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(130, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(650, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_11.setGeometry(QtCore.QRect(630, 100, 161, 31))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 60, 161, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_4.setGeometry(QtCore.QRect(130, 100, 161, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_12.setGeometry(QtCore.QRect(630, 140, 161, 31))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(590, 70, 31, 21))
        self.label_9.setObjectName("label_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab)
        self.pushButton_11.setGeometry(QtCore.QRect(870, 380, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("\n"
"background-color: rgb(85, 170, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_13.setGeometry(QtCore.QRect(130, 180, 161, 31))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 140, 161, 31))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_15.setGeometry(QtCore.QRect(130, 260, 161, 31))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_16.setGeometry(QtCore.QRect(130, 220, 161, 31))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_17.setGeometry(QtCore.QRect(630, 60, 161, 31))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_18.setGeometry(QtCore.QRect(50, 440, 341, 31))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab)
        self.pushButton_12.setGeometry(QtCore.QRect(180, 390, 90, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(580, 100, 41, 31))
        self.label_10.setObjectName("label_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(280, 410, 90, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 410, 90, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 410, 90, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(670, 410, 90, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(320, 380, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(120, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(410, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(690, 80, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit.setGeometry(QtCore.QRect(100, 210, 161, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 170, 161, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_7.setGeometry(QtCore.QRect(380, 130, 161, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_8.setGeometry(QtCore.QRect(380, 170, 161, 31))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_9.setGeometry(QtCore.QRect(660, 130, 161, 31))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(660, 170, 161, 31))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.line_3 = QtWidgets.QFrame(self.tab_3)
        self.line_3.setGeometry(QtCore.QRect(110, 110, 691, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(50, 130, 47, 31))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_6.setGeometry(QtCore.QRect(100, 130, 161, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_19.setGeometry(QtCore.QRect(140, 460, 341, 31))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_14.setGeometry(QtCore.QRect(140, 410, 90, 31))
        self.pushButton_14.setObjectName("pushButton_14")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 20, 101, 31))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(780, 10, 111, 41))
        self.pushButton_10.setStyleSheet("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 60, 971, 451))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_5)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(-5, 11, 990, 401))
        self.tableWidget.setStyleSheet("QTableView {\n"
"    selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 blue, stop: 1 white);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget_2.setGeometry(QtCore.QRect(-5, 11, 991, 411))
        self.tableWidget_2.setStyleSheet("QTableView {\n"
"    selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 blue, stop: 1 white);\n"
"}")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.tabWidget_2.addTab(self.tab_6, "")
        self.comboBox = QtWidgets.QComboBox(self.tab_4)
        self.comboBox.setGeometry(QtCore.QRect(160, 20, 81, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_13.setGeometry(QtCore.QRect(280, 20, 90, 31))
        self.pushButton_13.setObjectName("pushButton_13")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_4.setGeometry(QtCore.QRect(0, 70, 981, 431))
        self.tableWidget_4.setStyleSheet("QTableView {\n"
"    selection-background-color: qlineargradient(x1: 0, y1: 0, x2: 0.5, y2: 0.5,\n"
"                                stop: 0 blue, stop: 1 white);\n"
"}")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(630, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label1 = QtWidgets.QLabel(Form)
        self.label1.setGeometry(QtCore.QRect(50, 10, 121, 91))
        self.label1.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Sudan))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.dateEdit = QtWidgets.QDateEdit(Form)
        self.dateEdit.setGeometry(QtCore.QRect(740, 20, 147, 31))
        self.dateEdit.setAutoFillBackground(False)
        self.dateEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Sudan))
        self.dateEdit.setReadOnly(True)
        self.dateEdit.setObjectName("dateEdit")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Pharmacy Management"))
        self.pushButton_5.setText(_translate("Form", "Clear"))
        self.pushButton_6.setText(_translate("Form", "Delete"))
        self.pushButton_7.setText(_translate("Form", "Search"))
        self.pushButton_8.setText(_translate("Form", "Add"))
        self.label_6.setText(_translate("Form", "Customer Information"))
        self.label_7.setText(_translate("Form", "Medicine Information"))
        self.lineEdit_11.setPlaceholderText(_translate("Form", "Sale Price"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Customer Name"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Doctor Name"))
        self.lineEdit_12.setPlaceholderText(_translate("Form", "Quantity"))
        self.label_9.setText(_translate("Form", "M - ID"))
        self.pushButton_11.setText(_translate("Form", "Logout"))
        self.lineEdit_13.setPlaceholderText(_translate("Form", "City"))
        self.lineEdit_14.setPlaceholderText(_translate("Form", "Hospital Name"))
        self.lineEdit_15.setPlaceholderText(_translate("Form", "Cure name"))
        self.lineEdit_16.setPlaceholderText(_translate("Form", "zip if any"))
        self.lineEdit_17.setPlaceholderText(_translate("Form", "M - ID"))
        self.lineEdit_18.setPlaceholderText(_translate("Form", "M- ID to Search"))
        self.pushButton_12.setText(_translate("Form", "Update"))
        self.label_10.setText(_translate("Form", "USA $"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Sale"))
        self.pushButton.setText(_translate("Form", "Update"))
        self.pushButton_2.setText(_translate("Form", "Delete"))
        self.pushButton_3.setText(_translate("Form", "Add"))
        self.pushButton_4.setText(_translate("Form", "Clear"))
        self.label_2.setText(_translate("Form", "Medicine info"))
        self.label_3.setText(_translate("Form", "Price info"))
        self.label_4.setText(_translate("Form", "Company info"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Quantity"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Cure Name"))
        self.lineEdit_7.setPlaceholderText(_translate("Form", "Purchase Price"))
        self.lineEdit_8.setPlaceholderText(_translate("Form", "Sale Price"))
        self.lineEdit_9.setPlaceholderText(_translate("Form", "Supplier"))
        self.lineEdit_10.setPlaceholderText(_translate("Form", "Company"))
        self.label_8.setText(_translate("Form", "M - ID"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "M - ID"))
        self.lineEdit_19.setPlaceholderText(_translate("Form", "M- ID to Search"))
        self.pushButton_14.setText(_translate("Form", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Purchase"))
        self.pushButton_9.setText(_translate("Form", "Send to Excel"))
        self.pushButton_10.setText(_translate("Form", "Search with group"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "M ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Customer Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Doctor Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Hospital Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "City"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Zip"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Cure name"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Sale price"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "Quantity"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "Sale"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "m_id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "cure_name"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Form", "quantity"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Form", "purchase_price"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Form", "sale_price"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Form", "supplier"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Form", "company"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("Form", "purchase"))
        self.comboBox.setItemText(0, _translate("Form", "Sale"))
        self.comboBox.setItemText(1, _translate("Form", "purchase"))
        self.pushButton_13.setText(_translate("Form", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Items"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("Form", "C- ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("Form", "C- Name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("Form", "D- Name"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Mid -ID"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("Form", "S- price"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Customers"))
        self.label_5.setText(_translate("Form", "Today Date"))

